/* Concatenates the browser sim files into an ES module the Worker can
   import. The browser loads public/js/*.js as plain <script> tags; the
   Worker can't eval, so we generate server/sim.gen.mjs at build time. */

import { readFileSync, writeFileSync } from 'node:fs';

const FILES = ['util.js', 'parts.js', 'creature.js', 'world.js'];

let out = '/* GENERATED by scripts/build-sim.mjs — edit public/js/*.js instead */\n';
for (const f of FILES){
  out += `\n/* ================ public/js/${f} ================ */\n`;
  out += readFileSync(new URL(`../public/js/${f}`, import.meta.url), 'utf8');
}
out += `
export {
  Cell, World, PARTS, PART_KEYS, GEN_TITLES, ROMAN, FOOD_TYPES, NEWBIE_R, HUE_UNLOCKS, TRAIL_NAMES, TRAIL_UNLOCKS, SHAPE_NAMES, SHAPE_UNLOCKS, DYNASTY_TITLES,
  deriveStats, randomGenome, partCost, randomSpeciesName, isValidSpeciesName, growthNeedFor,
  capacityFor, genomeLevels, MOUTH_KEYS, ORGAN_SYSTEMS, TIDES, tideNumber, tideFor, ORDERS, weekNumber, orderFor,
  rand, randInt, pick, clamp, lerp, damp, angleLerp, dist, TAU
};
`;

writeFileSync(new URL('../server/sim.gen.mjs', import.meta.url), out);
console.log('server/sim.gen.mjs written');
